version: '3.5'

services:
  web:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/:/home/francois/Documents/app_twitter_learning/back/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo

