version: '3.5'

services:
  web:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=1 --threads=3 --worker-class=gthread twitterStream.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/Users/f.danselme/Documents/djangoTwitter/back/staticfiles
    ports:
      - 8000:8000
    networks:
      - esnet
    environment:
      - DEBUG=0
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/Users/f.danselme/Documents/djangoTwitter/back/staticfiles
    ports:
      - "0.0.0.0:1337:80"
    depends_on:
      - web
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    hostname: elasticsearch
    container_name: twitter_learning_elasticsearch
    networks:
      - esnet
    environment:
      - bootstrap.memory_lock=false
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9500:9500"
  client:
    image: appropriate/curl:latest
    command: "curl http://elasticsearch:9500"
    networks:
      - esnet

  

networks:
  esnet:
    driver: bridge  
volumes:
  static_volume:


