# Generated by Django 2.2 on 2019-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='interesting',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=280),
        ),
    ]
