# Generated by Django 2.2 on 2019-04-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0002_auto_20190410_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='interesting',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
