# Generated by Django 2.2 on 2019-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0003_auto_20190415_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='metaData',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
    ]
