# Generated by Django 2.2 on 2019-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0004_tweet_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterterm',
            name='user',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
