# Generated by Django 2.2 on 2019-04-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0005_filterterm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='emailUser',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
