# Generated by Django 2.2 on 2019-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0006_tweet_emailuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='emailUser',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
