# Generated by Django 2.2 on 2019-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0007_auto_20190419_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text_nettoye',
            field=models.CharField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
