# Generated by Django 2.2 on 2019-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0009_modelsaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsaved',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
