# Generated by Django 2.2 on 2019-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0010_modelsaved_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterterm',
            name='nameOfTheModel',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
