# Generated by Django 2.2 on 2019-05-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0011_filterterm_nameofthemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterterm',
            name='nameOfTheModel',
        ),
    ]
