# Generated by Django 2.2 on 2019-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamTwitter', '0012_remove_filterterm_nameofthemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsaved',
            name='keywords',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
