import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class AppConstants {
  TOKEN_HEADER = 'X-Auth-Token';
  DATA = 'DATA';
  DATA_LENGTH = 'DATA_LENGTH';
  ERROR = 'ERROR';
  UPDATE = 'UPDATE';
  REGISTRED = 'REGISTRED';
  EXIST_EMAIL = 'EXIST_EMAIL';
  USER = 'USER';
  ROLES = 'ROLES';
  USER_DETAILS = 'USER_DETAILS';
  TOKEN = 'TOKEN';
  MESSAGE = 'MESSAGE';
  MESSAGE_ERROR = 'MESSAGE_ERROR';
  CODE_ERROR = 'CODE_ERROR';
  TIMESTAMPS = 'TIMESTAMPS';
  SUBSCRIPTIONS = 'SUBSCRIPTIONS';

  APPLICATION_SINAY_PLATFORM = 'APPLICATION_SINAY_PLATFORM';
  APPLICATION_CATALOG = 'APPLICATION_CATALOG';
  APPLICATION_CABLE = 'APPLICATION_CABLE';
  APPLICATION_TWITTER = 'APPLICATION_TWITTER';

  WISH_LIST = 'WISH_LIST';
  WISH = 'WISH';
  APPLICATION_JSON = 'application/json';
  TYPE_DATA_SET = 'DATA_SET';
  TYPE_PACKAGE = 'PACKAGE';
}
